# Generated by Django 4.0.6 on 2022-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО водителя')),
                ('identification_card', models.IntegerField(max_length=9, verbose_name='Удостоверение личности, №')),
                ('driver_license', models.IntegerField(max_length=10, verbose_name='Водительское удостоверение')),
                ('car_info', models.TextField(verbose_name='Марка, модель авто, год выпуска')),
                ('car_number', models.CharField(max_length=8, verbose_name='Государственный номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО пассажира')),
                ('telephone_number', models.IntegerField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
            ],
        ),
    ]
